#!/usr/bin/python3

import sys
import os

# Adding the src directory for the impor
src_path = os.path.join(os.path.dirname(__file__), 'src')
sys.path.append(src_path)

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'  
def main():
    if len(sys.argv) <= 1:
        from model import train
        train.main()
    elif sys.argv[1] == 'test':
        from tests import test
        test.main()
    else:
        raise Exception("The arguments doesn't match")
if __name__ == '__main__':
    main()
